# Generated by Django 2.2.1 on 2020-05-20 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Packages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('price', models.FloatField()),
                ('socialMedia', models.TextField()),
                ('psotNo', models.IntegerField()),
                ('videoNo', models.IntegerField()),
                ('reportType', models.CharField(max_length=255)),
                ('language', models.CharField(max_length=255)),
                ('costomCompany', models.TextField()),
                ('target', models.TextField()),
                ('otherAd', models.TextField()),
                ('gurant', models.CharField(max_length=255)),
                ('status', models.IntegerField(default=1)),
            ],
        ),
    ]
