# Generated by Django 2.2.1 on 2020-05-21 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotations', '0002_auto_20200521_2156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotation',
            name='packNo',
            field=models.IntegerField(),
        ),
    ]
