# Generated by Django 2.2.1 on 2020-05-21 18:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quotations', '0003_auto_20200521_2202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotation',
            name='packNo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='packages.Packages'),
        ),
    ]
